name: release
on:
  release:
    types:
      - created

env:
  VERSION: ${{ github.event.release.tag_name != '' && github.event.release.tag_name | sed 's/v//' || 'v0.0.0' }}

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      - name: Run Test
        run: |
          pytest src/ --cov --junitxml=pytest.xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Replace version
        run: |
          sed -i "s/__version__ = '\(.*\)'/__version__ = '${{ env.VERSION }}'/" py_nullable/__version__.py

      - name: Build
        run: |
          python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_APITOKEN_FULL_ACCESS }}
