name: update_sphinxdoc
on:
  workflow_run:
    workflows:
      - "test"
    branches:
      - "main"
    types:
      - completed
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Branch
        run: |
          branchname="githubaction_sphinx_${{ env.GITHUB_SHA }}"
          echo "BRANCH_NAME=${branchname}" >> $GITHUB_ENV
          git checkout -b $branchname

      - name: Install dependencies ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      - name: sphinx build
        run: |
          sphinx-apidoc -f -o ./docs py_nullable
          sphinx-build -b html docs docs/_build/html

      - name: git config
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "79917704+github-actions[bot]@users.noreply.github.com"

      - name: git commit
        run: |
          git add docs/_build/html
          git commit -m "doc: sphinx update ${{ env.GITHUB_SHA }}"
          git push

      - name: pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: main
          pr_title: Sphinx Update ${{ env.GITHUB_SHA }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
